### ISSUE TITLE
go get github.com/lopezator/sqlfmt/... command failing

### ISSUE THREAD

**Issue by rootid** [lopezator/sqlfmt#1]
Go version - go1.9.2 darwin/amd64

``` # github.com/lopezator/sqlfmt/vendor/github.com/cockroachdb/cockroach/pkg/util/log/logtags
../../gocode/src/github.com/lopezator/sqlfmt/vendor/github.com/cockroachdb/cockroach/pkg/util/log/logtags/buffer.go:122:10: undefined: strings.Builder
# github.com/lopezator/sqlfmt/vendor/github.com/cockroachdb/cockroach/pkg/util/pretty
../../gocode/src/github.com/lopezator/sqlfmt/vendor/github.com/cockroachdb/cockroach/pkg/util/pretty/pretty.go:48:9: undefined: strings.Builder
../../gocode/src/github.com/lopezator/sqlfmt/vendor/github.com/cockroachdb/cockroach/pkg/util/pretty/pretty.go:248:29: undefined: strings.Builder
# github.com/lopezator/sqlfmt/vendor/github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror
../../gocode/src/github.com/lopezator/sqlfmt/vendor/github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror/errors.go:48:8: undefined: strings.Builder```

**Comment by lopezator** [comment]
As cockroachdb is a direct dependency of sqlfmt, specifically the cockroach-gen version, sqlfmt has the same limitations as cockroach-gen has.

Refering specifically to your issue, you can see in cockroach-gen's codebase:

https://github.com/cockroachdb/cockroach-gen/blob/master/build/go-version-check.sh#L8-L9

That it requires at least go 1.10, so unfortunately it won't work with go 1.9.2. The only solution is updating.

As a result of your issue, I will add that information to README to warn other users. Thank you.
